GET http://localhost:3000/subscribers

###

GET http://localhost:3000/subscribers/5f3dd6e55f62fca282a09877

###

POST http://localhost:3000/subscribers
Content-type: application/json

{
    "name": "Amazing Person",
    "subscribedToChannel": "Web Dev Simplified"
}

###

DELETE http://localhost:3000/subscribers/5f3dd6e55f62fca282a09877

###

PATCH http://localhost:3000/subscribers/5f3dd6e55f62fca282a09877
Content-type: application/json

{
    "name": "New Name"
}